export const actionTypes = {
    GET_CATEGORY_ITEMS: 'GET_CATEGORY_ITEMS',
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',

    GET_CART_ITEMS: 'GET_CART_ITEMS',
    ADD_ITEM_CART: 'ADD_ITEM_CART',
    REMOVE_ITEM_CART: 'REMOVE_ITEM_CART',
    INCREASE_ITEM_CART: 'INCREASE_ITEM_CART',
    DECREASE_ITEM_CART: 'DECREASE_ITEM_CART',
    CLEAR_CART: 'CLEAR_CART',

    LOGIN_USER: 'LOGIN_USER',
    LOGOUT_USER: 'LOGOUT_USER'

}